### ISSUE TITLE
Duplicate codes for linked list

### ISSUE THREAD

**Issue by FR4NKESTI3N** [OpenGenus/cosmos#3934]
there is data_structures/src/list/singly_linked_list, but there is also a code for same problem in data_structures/linked_list/
One of them ought to be removed.

**Comment by rucha174** [comment]
Looks like this has been fixed

**Comment by FR4NKESTI3N** [comment]
@rucha174 Sorry, I had written wrong file path. Both directories still exist in repo.

**Comment by rucha174** [comment]
Is the filename correct?

**Comment by arnavb** [comment]
@FR4NKESTI3N @rucha174 If either of you would like to resolve this issue, then by all means go for it! Make sure to reference this issue however.

**Comment by rucha174** [comment]
I have sent a PR. Please review it.

**Comment by code-blooded** [comment]
Why is this issue still open ? @arnavb @rucha174

**Comment by arnavb** [comment]
@code-blooded The old directory isn't completely gone yet. We moved from one file to removing the whole directory, which is pretty much a duplicate of the other one.

**Comment by nisarg1499** [comment]
@arnavb Still same code of linked list is seen in both the paths.
Is this issue still open?

**Comment by rucha174** [comment]
@arnavb Hello! Should I make the required changes in the code?

**Comment by nitashadhingra** [comment]
under GSSoc i would like to contribute @AdiChat

**Comment by shreeya13garg** [comment]
I want to contribute in it..I think I would be able to remove the duplicate directory.

**Comment by arnavb** [comment]
@shreeya13garg / @nitashadhingra One of you can create a PR and fix this.

**Comment by shreeya13garg** [comment]
I have removed the singly linked list from  data_structures/src/list/singly_linked_list to remove duplicates. Should I push it on Github?

**Comment by shreeya13garg** [comment]
I have cloned the cosmos repository and committed the changes i.e removing duplicate files now I need permission to push it on github

**Comment by shreeya13garg** [comment]
My PR in which I have added the modified code-:https://github.com/shreeya13garg/cosmos_PR 
If there is any error let me know.

**Comment by arnavb** [comment]
@shreeya13garg That isn't how you create a pull request. I think you should follow this [guide](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) and become proficient with git.

**Comment by hanzohasashi33** [comment]
Can I take up this issue if it is still open ? @arnavb

**Comment by arnavb** [comment]
@hanzohasashi33 Sure. All you have to do is delete the extra folder, basically.

**Comment by hanzohasashi33** [comment]
Looks like there is no duplicate folder in data_structures/ for linked list.

**Comment by shreeya13garg** [comment]
Yeah, I have already solved it. This issue has been solved.

**Comment by saviourcode** [comment]
@arnavb, According to @shreeya13garg, this issue has been resolved, kindly close this issue. It will help others to focus on other pending issues. :smiley:
